---
title: "Tidying data"
author: "Felicia Cruz"
date: "8/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
```
```{r}
wb_indicators <- read_csv(here("data", "wb_indicators.csv"), na = c("..", ""))


```
## Reshape so that year is a single column
```{r}
wb_indicators_long <- wb_indicators %>% 
  pivot_longer(cols = '2001 [YR2001]': '2020 [YR2020]', 
               names_to = "year", 
               values_to = "indicator_value") 

```

## Clean up the year column
```{r}
wb_data_sep <- wb_indicators_long %>% 
  separate(col = year, into = c("year", "year_chr"), sep = " ") %>% 
  select(-year_chr, -'Country Code', -'Series Code') 

```

## Use pivot_wider to get all indicators in their own column
```{r}
wb_data_tidy <- wb_data_sep %>% 
  drop_na('Series Name') %>%  
  pivot_wider(names_from = 'Series Name',
              values_from = indicator_value)
```

## Cleaning/Wrangling
```{r}
# clean up the column names
names(wb_data_tidy) <- c("country", "year", "access_clean_fuels", "access_electricity", "co2_emissions", "fossil_fuel_consumption", "water_stress")

wb_data_tidy <- wb_data_tidy %>% 
  rename(country_name = country,
         electricity = access_electricity)
```


## Practice pivot_longer & pivot_wider
```{r}
df <- tribble(
  ~name, ~A, ~B, ~C,
  "teddy", 4, 5, 6,
  "khora", 9, 10, 11
)

df

# A, B, C are different dog food types --> convert to tidy structure 
df_long <- df %>% 
  pivot_longer(col = A:C, names_to = "dog_food_type", values_to = "rankings")

df_long

# show that pivot_wider is just the inverse of pivot_longer (if using same columns)
df_wide <- df_long %>% 
  pivot_wider(names_from = dog_food_type, values_from = rankings)

df_wide
```

